"""add marketing_goal to offers

Revision ID: d7421f314b0f
Revises: f59812f4df55
Create Date: 2026-03-25 19:39:50.452857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7421f314b0f'
down_revision: Union[str, None] = 'f59812f4df55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('marketing_goal', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'marketing_goal')
    # ### end Alembic commands ###
