"""initial tables

Revision ID: f59812f4df55
Revises: 
Create Date: 2026-03-25 02:12:36.409527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f59812f4df55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('preview_uri', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_scope_id'), 'assets', ['scope_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_scope_id'), 'knowledge_items', ['scope_id'], unique=False)
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('merchant_type', sa.String(length=32), nullable=False),
    sa.Column('default_locale', sa.String(length=16), nullable=False),
    sa.Column('supported_locales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_plans',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('source_mode', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('target_audience_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_scenario_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('key_points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_asset_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('score_relevance', sa.Float(), nullable=True),
    sa.Column('score_conversion', sa.Float(), nullable=True),
    sa.Column('score_asset_readiness', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_plans_merchant_id'), 'topic_plans', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_topic_plans_offer_id'), 'topic_plans', ['offer_id'], unique=False)
    op.create_table('asset_slices',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('slice_type', sa.String(length=32), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('usage_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scene_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selling_point_refs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel_fit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('proof_score', sa.Float(), nullable=True),
    sa.Column('reuse_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_slices_asset_id'), 'asset_slices', ['asset_id'], unique=False)
    op.create_table('offers',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('offer_type', sa.String(length=32), nullable=False),
    sa.Column('offer_model', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('target_audience_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_scenarios_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('core_selling_points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proofs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pricing_info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_index(op.f('ix_asset_slices_asset_id'), table_name='asset_slices')
    op.drop_table('asset_slices')
    op.drop_index(op.f('ix_topic_plans_offer_id'), table_name='topic_plans')
    op.drop_index(op.f('ix_topic_plans_merchant_id'), table_name='topic_plans')
    op.drop_table('topic_plans')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_knowledge_items_scope_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_assets_scope_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
